// lib/data.js
export const projects = [
  {
    slug: 'plant-disease-cnn',
    title: 'Plant Disease Identification & Pesticide Recommendation (CNN)',
    summary: 'CNN-based classifier with pesticide suggestions; paper published in IJIRCCE.',
    image: '/images/projects/plant-disease.jpg',
    link: 'https://github.com/Yasesvi-Reddy-Pebbeti/Plant-Disease-Identification-and-Pestiside-Recmmendation-Using-CNN',
    tags: ['Python','TensorFlow/PyTorch','CV'],
    dates: 'Nov 2023 – Jun 2024',
  },
  {
    slug: 'movie-recs',
    title: 'Content-Based Movie Recommendation System',
    summary: 'Recommends similar movies with TF-IDF and cosine similarity; simple web UI.',
    image: '/images/projects/movie-recs.jpg',
    link: 'https://github.com/Yasesvi-Reddy-Pebbeti/Content-Based-Movie-Recomendation-System',
    tags: ['Python','Pandas','NLP'],
    dates: 'Jul 2023 – Sep 2023',
  },
  {
    slug: 'software-defects',
    title: 'Software Defects Classification',
    summary: 'Led a team building an ML model for automated defect triage and accuracy optimization.',
    image: '/images/projects/defects.jpg',
    link: 'https://github.com/YOUR_LINK_OR_LEAVE_EMPTY',
    tags: ['Python','Scikit-learn','EDA'],
    dates: 'Aug 2024 – Dec 2024',
  },
  {
    slug: 'blockchain-auth',
    title: 'Authentication of Product & Counterfeit Elimination (Blockchain)',
    summary: 'Python-based blockchain auth with digital signatures & QR codes for real-time verification.',
    image: '/images/projects/blockchain.jpg',
    link: 'https://github.com/YOUR_LINK_OR_LEAVE_EMPTY',
    tags: ['Blockchain','Python','Security'],
    dates: 'Aug 2024 – Dec 2024',
  },
  {
    slug: 'syscall-kernel',
    title: 'Kernel Module for System Call Logging',
    summary: 'Linux kernel module in C to log syscalls and track processes via dmesg.',
    image: '/images/projects/kernel.jpg',
    link: 'https://github.com/YOUR_LINK_OR_LEAVE_EMPTY',
    tags: ['C','Linux Kernel'],
    dates: 'Aug 2024 – Dec 2024',
  },
  {
    slug: 'parallel-sorting',
    title: 'Parallel Sorting: Implementation, Profiling & Analysis',
    summary: 'Merge Sort & QuickSort with OpenMP, MPI, and Pthreads; gprof profiling and automated CSV → plots.',
    image: '/images/projects/parallel-sort.jpg',
    link: 'https://github.com/YOUR_LINK_OR_LEAVE_EMPTY',
    tags: ['C/C++','OpenMP','MPI','Pthreads','gprof','Python'],
    dates: 'Jan 2025 – May 2025',
  },
  {
    slug: 'finance-tracker',
    title: 'Finance Tracker (Flutter + Google Sheets API)',
    summary: 'Cross-platform expense tracking syncing to Google Sheets with admin reporting.',
    image: '/images/projects/finance.jpg',
    link: 'https://github.com/YOUR_LINK_OR_LEAVE_EMPTY',
    tags: ['Flutter','Dart','Google Sheets API'],
    dates: 'Jan 2025 – May 2025',
  },
  {
    slug: 'brain-tumor-cnn',
    title: 'Brain Tumor Classification (CNN + Grad-CAM)',
    summary:
      'End-to-end CNN pipeline with data augmentation, class-balanced training, ROC-AUC evaluation, and Grad-CAM visualizations to highlight tumor regions. (Rebuilding after data loss.)',
    image: '/images/projects/brain-tumor.jpg',
    link: 'https://github.com/YOUR_LINK_OR_LEAVE_EMPTY',
    tags: ['PyTorch','Grad-CAM','Medical Imaging'],
    dates: 'Jan 2025 – May 2025',
  },
  {
    slug: 'd4-rotation-equiv',
    title: 'Rotation Equivariance in CNNs Using the D4 Group',
    summary:
      'D4-equivariant CNN (0°, 90°, 180°, 270°) with e2cnn on UC Merced Land Use to improve robustness to rotations.',
    image: '/images/projects/d4.jpg',
    link: 'https://github.com/YOUR_LINK_OR_LEAVE_EMPTY',
    tags: ['e2cnn','Equivariance','Satellite'],
    dates: 'May 2025 – Aug 2025',
  },
];
